version: 3

tasks:
  run-registrar:
    - go run ./cmd/services/registrar {{.CLI_ARGS}}
  run-logging:
    - go run ./cmd/services/logging {{.CLI_ARGS}}

  run-business:
    - go run ./cmd/services/business {{.CLI_ARGS}}
